### ISSUE TITLE
brew tap dirien/homebrew-dirien fail on Apple Silicon M1

### ISSUE THREAD

**Issue by devopsmariocom** [dirien/homebrew-dirien#1]
I was looking to give tfu try but failed on brew install

```
Error: Invalid formula: /opt/homebrew/Library/Taps/dirien/homebrew-dirien/Formula/k3sair.rb
formulae require at least a URL
Error: Cannot tap dirien/dirien: invalid syntax in tap!
```

Solution could be either building k3sair ARM version and add it to formula or install x86 arch on M1 and let rosetta 2 do the magic.

**Comment by dirien** [comment]
hi @elmariofredo, will do this create a arm version

**Comment by dirien** [comment]
@elmariofredo done. I crated an ARM version for darwin and linux OS. Thanks for pointing this out!
